#!/bin/bash
# vim: ts=2 sw=2 sts=2 et
# see https://android.googlesource.com/platform/tools/idea/+/studio-master-dev/platform/build-scripts/resources/linux/scripts/executable-template.sh

ANDROID_HOME=${HOME}/tools/adt-bundle-linux-x86_64/sdk
ANDROID_NDK_ROOT=${ANDROID_HOME}/ndk-bundle
ANDROID_NDK_HOME=${ANDROID_NDK_ROOT}
ANDROID_EMULATOR_USE_SYSTEM_LIBS=1

JRE_LIST=(/usr/lib/jvm/intellij-jdk
  /opt/intellij-idea-ultimate-edition/jre64
  /usr/lib/jvm/java-8-openjdk
  /usr/lib/jvm/java-11-openjdk
  /usr/lib/jvm/java-10-openjdk
)

for D in ${JRE_LIST[@]}
do
  [ -d ${D} ] && STUDIO_JDK=${D} && unset D && break
done
unset JRE_LIST

# https://github.com/ganadist/scripts/blob/master/.studio64.vmoptions
STUDIO_VM_OPTIONS="${HOME}/.studio64.vmoptions"
STUDIO_PROPERTIES="$HOME/.idea.properties"

#IBUS_ENABLE_SYNC_MODE=1

sdenv \
  ANDROID_HOME ANDROID_NDK_ROOT ANDROID_NDK_HOME STUDIO_JDK \
  ANDROID_EMULATOR_USE_SYSTEM_LIBS STUDIO_VM_OPTIONS \
  STUDIO_PROPERTIES
