#!/bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

# path junk

if [ $UID -eq 0 ]; then
        PATH=~root/bin:$PATH
else
        PATH=${HOME}/bin:$PATH
fi

LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
#LIBXCB_ALLOW_SLOPPY_LOCK=1
MOONLIGHT_OVERRIDES="shapecache=yes,converter=ffmpeg"
export LIBXCB_ALLOW_SLOPPY_LOCK MOONLIGHT_OVERRIDES 
export LD_LIBRARY_PATH PATH

