#!/bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

export EMAIL="ganadist@gmail.com"
export FULLNAME="Young-Ho Cha"

#export DEBEMAIL=$EMAIL
#export DEBFULLNAME=$FULLNAME

#export GIT_AUTHOR_NAME=$FULLNAME
#export GIT_COMMITTER_NAME=$FULLNAME
#export GIT_AUTHOR_EMAIL=$EMAIL
#export GIT_COMMITTER_EMAIL=$EMAIL

export IRCNICK=${USERNAME}
export IRCNAME=${FULLNAME}
export IRCSERVER=irc.hanirc.org
export IRC_SERVERS_FILE="$HOME/.irc-serv"

export CVS_RSH="ssh"
export CVSREAD=yes
export MANWIDTH=80
EDITOR=vim
if ( which sublime_text > /dev/null 2>&1 ); then
	[ -z $DISPLAY ] || EDITOR=sublime_text
fi
export EDITOR
export VISUAL=vim
#export CCACHE_DIR=$HOME/.ccache
export USE_CCACHE=1

export INPUTRC="~/.inputrc"
export MAIL="${HOME}/mail/inbox"

export RLWRAP_HOME=~/.cache/rlwrap/
#export GTK_IM_MODULE=ibus

export LC_MESSAGES=ko_KR.UTF-8
export LC_ALL=ko_KR.UTF-8

# path junk

if [ $UID -eq 0 ]; then
        PATH=~root/bin:$PATH
else
        PATH=${HOME}/bin:$PATH
fi

# less options
LESS=FRSX

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"

export MPD_HOST=127.0.0.1
export MPD_PORT=6600

FT2_SUBPIXEL_HINTING=1

LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
#LIBXCB_ALLOW_SLOPPY_LOCK=1
MOONLIGHT_OVERRIDES="shapecache=yes,converter=ffmpeg"
export PYTHONSTARTUP LIBXCB_ALLOW_SLOPPY_LOCK MOONLIGHT_OVERRIDES 
export LD_LIBRARY_PATH FT2_SUBPIXEL_HINTING PATH

